# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  pod 'Masonry'
  #工具
  pod 'XyWidget', '~> 1.2.1'
  #提示框
  pod 'SVProgressHUD'
  pod 'ObjectMapper'
  pod 'Kingfisher', '~> 4.10.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire', '~> 5.4.1'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'VHLiveSDK', '~> 5.0.0'
  pod 'SwiftyJSON'
  pod 'YYCache'
  pod 'SDWebImage', '~> 5.0.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MJRefresh','~> 3.1.0'
  pod 'FDFullscreenPopGesture', '~> 1.1'
  pod 'TZScrollViewPopGesture'
  pod 'YYModel'
#  pod 'MBProgressHUD'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
